import { AppState } from 'src/state';
import { ApplicationModal, PopupContent } from './actions';
export declare function useBlockNumber(): number | undefined;
export declare function useModalOpen(modal: ApplicationModal): boolean;
export declare function useToggleModal(modal: ApplicationModal): () => void;
export declare function useWalletModalToggle(): () => void;
export declare function usePoolDetailnModalToggle(): () => void;
export declare function useAddPopup(): (content: PopupContent, key?: string) => void;
export declare function useRemovePopup(): (key: string) => void;
export declare function useActivePopups(): AppState['papplication']['popupList'];
